# Generated by Django 4.1.3 on 2022-11-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('blue', 'Azul'), ('red', 'Rojo'), ('orange', 'Naranja'), ('green', 'Verde')], default='blue', max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
