# Generated by Django 4.1.3 on 2022-11-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_color_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='orden',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('red', 'red'), ('orange', 'orange'), ('green', 'green')], default='blue', max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='N', max_length=6),
        ),
    ]
