# Generated by Django 4.1.3 on 2022-11-09 18:11

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.SlugField(max_length=4)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=tasks.models.today)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
