# Generated by Django 4.1.3 on 2022-11-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.SlugField(max_length=4, unique=True),
        ),
    ]
