# Generated by Django 4.1.3 on 2022-12-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_project_progress_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='progress_value',
        ),
    ]
